#############################################################################
# Makefile for building: SimpleDrawer
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sat Aug 25 14:13:24 2012
# Project:  SimpleDrawer.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile SimpleDrawer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt/mkspecs/linux-g++-64 -I. -I/usr/lib64/qt/include/QtCore -I/usr/lib64/qt/include/QtGui -I/usr/lib64/qt/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/usr/lib64/qt/lib
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt/lib -lQtGui -L/usr/lib64/qt/lib -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		drawingform.cpp \
		drawingarea.cpp \
		scale.cpp \
		linepoints.cpp moc_drawingform.cpp \
		moc_drawingarea.cpp
OBJECTS       = main.o \
		drawingform.o \
		drawingarea.o \
		scale.o \
		linepoints.o \
		moc_drawingform.o \
		moc_drawingarea.o
DIST          = /usr/lib64/qt/mkspecs/common/g++.conf \
		/usr/lib64/qt/mkspecs/common/unix.conf \
		/usr/lib64/qt/mkspecs/common/linux.conf \
		/usr/lib64/qt/mkspecs/qconfig.pri \
		/usr/lib64/qt/mkspecs/modules/qt_phonon.pri \
		/usr/lib64/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib64/qt/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt/mkspecs/features/qt_config.prf \
		/usr/lib64/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt/mkspecs/features/default_pre.prf \
		/usr/lib64/qt/mkspecs/features/release.prf \
		/usr/lib64/qt/mkspecs/features/default_post.prf \
		/usr/lib64/qt/mkspecs/features/warn_on.prf \
		/usr/lib64/qt/mkspecs/features/qt.prf \
		/usr/lib64/qt/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt/mkspecs/features/moc.prf \
		/usr/lib64/qt/mkspecs/features/resources.prf \
		/usr/lib64/qt/mkspecs/features/uic.prf \
		/usr/lib64/qt/mkspecs/features/yacc.prf \
		/usr/lib64/qt/mkspecs/features/lex.prf \
		/usr/lib64/qt/mkspecs/features/include_source_dir.prf \
		SimpleDrawer.pro
QMAKE_TARGET  = SimpleDrawer
DESTDIR       = 
TARGET        = SimpleDrawer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_drawingform.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SimpleDrawer.pro  /usr/lib64/qt/mkspecs/linux-g++-64/qmake.conf /usr/lib64/qt/mkspecs/common/g++.conf \
		/usr/lib64/qt/mkspecs/common/unix.conf \
		/usr/lib64/qt/mkspecs/common/linux.conf \
		/usr/lib64/qt/mkspecs/qconfig.pri \
		/usr/lib64/qt/mkspecs/modules/qt_phonon.pri \
		/usr/lib64/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib64/qt/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt/mkspecs/features/qt_config.prf \
		/usr/lib64/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt/mkspecs/features/default_pre.prf \
		/usr/lib64/qt/mkspecs/features/release.prf \
		/usr/lib64/qt/mkspecs/features/default_post.prf \
		/usr/lib64/qt/mkspecs/features/warn_on.prf \
		/usr/lib64/qt/mkspecs/features/qt.prf \
		/usr/lib64/qt/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt/mkspecs/features/moc.prf \
		/usr/lib64/qt/mkspecs/features/resources.prf \
		/usr/lib64/qt/mkspecs/features/uic.prf \
		/usr/lib64/qt/mkspecs/features/yacc.prf \
		/usr/lib64/qt/mkspecs/features/lex.prf \
		/usr/lib64/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt/lib/libQtGui.prl \
		/usr/lib64/qt/lib/libQtCore.prl
	$(QMAKE) -o Makefile SimpleDrawer.pro
/usr/lib64/qt/mkspecs/common/g++.conf:
/usr/lib64/qt/mkspecs/common/unix.conf:
/usr/lib64/qt/mkspecs/common/linux.conf:
/usr/lib64/qt/mkspecs/qconfig.pri:
/usr/lib64/qt/mkspecs/modules/qt_phonon.pri:
/usr/lib64/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/lib64/qt/mkspecs/features/qt_functions.prf:
/usr/lib64/qt/mkspecs/features/qt_config.prf:
/usr/lib64/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt/mkspecs/features/default_pre.prf:
/usr/lib64/qt/mkspecs/features/release.prf:
/usr/lib64/qt/mkspecs/features/default_post.prf:
/usr/lib64/qt/mkspecs/features/warn_on.prf:
/usr/lib64/qt/mkspecs/features/qt.prf:
/usr/lib64/qt/mkspecs/features/unix/thread.prf:
/usr/lib64/qt/mkspecs/features/moc.prf:
/usr/lib64/qt/mkspecs/features/resources.prf:
/usr/lib64/qt/mkspecs/features/uic.prf:
/usr/lib64/qt/mkspecs/features/yacc.prf:
/usr/lib64/qt/mkspecs/features/lex.prf:
/usr/lib64/qt/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt/lib/libQtGui.prl:
/usr/lib64/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile SimpleDrawer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SimpleDrawer1.0.0 || $(MKDIR) .tmp/SimpleDrawer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SimpleDrawer1.0.0/ && $(COPY_FILE) --parents drawingform.h drawingarea.h scale.h linepoints.h .tmp/SimpleDrawer1.0.0/ && $(COPY_FILE) --parents main.cpp drawingform.cpp drawingarea.cpp scale.cpp linepoints.cpp .tmp/SimpleDrawer1.0.0/ && $(COPY_FILE) --parents drawingform.ui .tmp/SimpleDrawer1.0.0/ && (cd `dirname .tmp/SimpleDrawer1.0.0` && $(TAR) SimpleDrawer1.0.0.tar SimpleDrawer1.0.0 && $(COMPRESS) SimpleDrawer1.0.0.tar) && $(MOVE) `dirname .tmp/SimpleDrawer1.0.0`/SimpleDrawer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SimpleDrawer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_drawingform.cpp moc_drawingarea.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_drawingform.cpp moc_drawingarea.cpp
moc_drawingform.cpp: drawingform.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) drawingform.h -o moc_drawingform.cpp

moc_drawingarea.cpp: scale.h \
		linepoints.h \
		drawingarea.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) drawingarea.h -o moc_drawingarea.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_drawingform.h
compiler_uic_clean:
	-$(DEL_FILE) ui_drawingform.h
ui_drawingform.h: drawingform.ui \
		drawingarea.h \
		scale.h \
		linepoints.h
	/usr/lib64/qt/bin/uic drawingform.ui -o ui_drawingform.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp drawingform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

drawingform.o: drawingform.cpp drawingform.h \
		ui_drawingform.h \
		drawingarea.h \
		scale.h \
		linepoints.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawingform.o drawingform.cpp

drawingarea.o: drawingarea.cpp drawingarea.h \
		scale.h \
		linepoints.h \
		ui_drawingform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawingarea.o drawingarea.cpp

scale.o: scale.cpp scale.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scale.o scale.cpp

linepoints.o: linepoints.cpp linepoints.h \
		scale.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linepoints.o linepoints.cpp

moc_drawingform.o: moc_drawingform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_drawingform.o moc_drawingform.cpp

moc_drawingarea.o: moc_drawingarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_drawingarea.o moc_drawingarea.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

